/* eslint-disable */
export default async () => {
    const t = {
        ["./playlists/playlist.entity"]: await import("./playlists/playlist.entity"),
        ["./songs/song.entity"]: await import("./songs/song.entity"),
        ["./users/user.entity"]: await import("./users/user.entity"),
        ["./artists/artist.entity"]: await import("./artists/artist.entity")
    };
    return { "@nestjs/swagger": { "models": [[import("./users/user.entity"), { "User": { id: { required: true, type: () => Number }, firstName: { required: true, type: () => String }, lastName: { required: true, type: () => String }, email: { required: true, type: () => String }, password: { required: true, type: () => String }, twoFASecret: { required: true, type: () => String }, enable2FA: { required: true, type: () => Boolean }, apiKey: { required: true, type: () => String }, playLists: { required: true, type: () => [t["./playlists/playlist.entity"].Playlist] } } }], [import("./playlists/playlist.entity"), { "Playlist": { id: { required: true, type: () => Number }, name: { required: true, type: () => String }, songs: { required: true, type: () => [t["./songs/song.entity"].Song] }, user: { required: true, type: () => t["./users/user.entity"].User } } }], [import("./songs/song.entity"), { "Song": { id: { required: true, type: () => Number }, title: { required: true, type: () => String }, releasedDate: { required: true, type: () => Date }, duration: { required: true, type: () => Date }, lyrics: { required: true, type: () => String }, playList: { required: true, type: () => t["./playlists/playlist.entity"].Playlist }, artists: { required: true, type: () => [t["./artists/artist.entity"].Artist] } } }], [import("./artists/artist.entity"), { "Artist": { id: { required: true, type: () => Number }, user: { required: true, type: () => t["./users/user.entity"].User }, songs: { required: true, type: () => [t["./songs/song.entity"].Song] } } }]], "controllers": [[import("./app.controller"), { "AppController": { "getHello": { type: String }, "getProfile": { type: Object } } }], [import("./songs/songs.controller"), { "SongsController": { "findAll": {}, "create": { type: t["./songs/song.entity"].Song }, "findOne": { type: t["./songs/song.entity"].Song }, "update": {}, "remove": {} } }], [import("./playlists/playlists.controller"), { "PlaylistsController": { "create": { type: t["./playlists/playlist.entity"].Playlist } } }], [import("./auth/auth.controller"), { "AuthController": { "singup": { type: t["./users/user.entity"].User }, "login": { type: Object }, "enable2FA": { type: Object }, "validate2FA": {}, "disable2FA": {}, "getProfile": {} } }]] } };
};